name: Flutter Build & Deploy

on:
  push:
    branches:
      - main
      - uat
      - distribution-ios

jobs:

  Flutter-Ios-Deployment:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/distribution-testflight'

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter clean
      - run: flutter pub get

      - run: flutter build ios --config-only -t ./lib/main.dart
      - uses: yukiarrr/ios-build-action@v1.11.1
        with:
          project-path: ios/Runner.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: ios/Runner.xcworkspace
          output-path: ios/app-release.ipa
          increment-build-number: testflight
          bundle-identifier: com.linhndq.alpha
          app-store-connect-api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          app-store-connect-api-key-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          app-store-connect-api-key-base64: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZzZIM0w4clpZNlc0TUpibG8KYmlsNFpwQklMMFNvNEJCaVBmYmNucjRmTE9TZ0NnWUlLb1pJemowREFRZWhSQU5DQUFTeDlqRlBXWnVDRDVNcgpWcjVkdFVjY1JLYVlUVDFPVXlvbUQ3OGU3ZkJhZU9zN0NSRHhLd3ExNE5CRUltY3RPc0FYZDVoL3JRNHcwUmZLCjJvTFdrcGJoCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0='

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'ios/app-release.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}