name: Flutter Build & Deploy

on:
  push:
    branches:
      - main
      - uat
      - distribution-ios

jobs:

  Flutter-Ios-Deployment:
    runs-on: macos-latest
    if: github.ref == 'refs/distribution-testflight/main'

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter clean
      - run: flutter pub get

      - name: Build for Production
        if: github.ref == 'refs/heads/distribution-testflight'
        run: flutter build ios --config-only -t ./lib/main.dart --release

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'path/to/application.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}